# Vectors and Matrices

## Setup

In [ ]:
import numpy as np
print(f"NumPy Version: {np.__version__}")

NumPy Version: 2.0.2


## Definitions and Notations

### Scalar
A scalar is just a single number.

In [ ]:
# A scalar is a single number.
s = 10
print(f"Scalar (s):\n{s}")

Scalar (s):
10


### Vector

A vector is an array of numbers. We can represent it as a 1D NumPy array.

In [ ]:
# A vector is a 1D array of numbers.
v = np.array([1, 2, 3, 4])
print(f"Vector (v):\n{v}")
print(f"Shape of v: {v.shape}")

Vector (v):
[1 2 3 4]
Shape of v: (4,)


### Matrix

A matrix is a 2D array of numbers with rows and columns. We can represent it as a 2D NumPy array.

In [ ]:
# A matrix is a 2D array (a grid) of numbers.
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(f"Matrix (A):\n{A}")
print(f"Shape of A (rows, columns): {A.shape}")

Matrix (A):
[[1 2 3]
 [4 5 6]]
Shape of A (rows, columns): (2, 3)


## Scalar and Vector Operations

In [ ]:
s = 5
v = np.array([2, 4, 6])

# Scalar-Vector Multiplication
mult_result = s * v
print(f"{s} * {v} = {mult_result}")

# Scalar-Vector Addition
add_result = s + v
print(f"{s} + {v} = {add_result}")

# Vector-Scalar Division
div_result = v / s
print(f"{v} / {s} = {div_result}")

5 * [2 4 6] = [10 20 30]
5 + [2 4 6] = [ 7  9 11]
[2 4 6] / 5 = [0.4 0.8 1.2]


## Vector-Vector Operations
These operations involve two vectors of the same size.

In [ ]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

# Vector Addition
add_result = u + v
print(f"{u} + {v} = {add_result}")

# Vector Subtraction
sub_result = u - v
print(f"{u} - {v} = {sub_result}")

# Element-wise (Hadamard) Product
element_wise_prod = u * v
print(f"Element-wise product of {u} and {v} = {element_wise_prod}")

# Dot Product
# It can be calculated using np.dot() or the @ operator.
dot_prod = np.dot(u, v) # u @ v
print(f"Dot product of {u} and {v} = {dot_prod}")

[1 2 3] + [4 5 6] = [5 7 9]
[1 2 3] - [4 5 6] = [-3 -3 -3]
Element-wise product of [1 2 3] and [4 5 6] = [ 4 10 18]
Dot product of [1 2 3] and [4 5 6] = 32


## Matrix Operations

### Scalar-Matrix Operations

Performing an operation with a scalar on a matrix applies the operation to every element.

In [ ]:
s = 10
C = np.array([[1, 2], [3, 4]])

# Scalar-Matrix Addition
add_result = s + C
print(f"Scalar Addition:\n{s} +\n{C}\n=\n{add_result}\n")

# Scalar-Matrix Multiplication
mult_result = s * C
print(f"Scalar Multiplication:\n{s} *\n{C}\n=\n{mult_result}")

Scalar Addition:
10 +
[[1 2]
 [3 4]]
=
[[11 12]
 [13 14]]

Scalar Multiplication:
10 *
[[1 2]
 [3 4]]
=
[[10 20]
 [30 40]]


### Matrix Addition and Subtraction

To add or subtract matrices, they must have the same dimensions. The operation is performed element-wise.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix Addition
add_result = A + B
print(f"Matrix Addition:\n{A}\n+\n{B}\n=\n{add_result}\n")

# Matrix Subtraction
sub_result = A - B
print(f"Matrix Subtraction:\n{A}\n-\n{B}\n=\n{sub_result}")

Matrix Addition:
[[1 2]
 [3 4]]
+
[[5 6]
 [7 8]]
=
[[ 6  8]
 [10 12]]

Matrix Subtraction:
[[1 2]
 [3 4]]
-
[[5 6]
 [7 8]]
=
[[-4 -4]
 [-4 -4]]


### Matrix Transpose

The transpose of a matrix swaps its rows and columns.

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Transpose using .T attribute
A_t = A.T
print(f"Original Matrix (A) with shape {A.shape}:\n{A}\n")
print(f"Transposed Matrix (A.T) with shape {A_t.shape}:\n{A_t}")

# A property of transpose is that transposing twice returns the original matri
print("\nVerifying (A.T).T == A:")
print((A.T).T)

Original Matrix (A) with shape (2, 3):
[[1 2 3]
 [4 5 6]]

Transposed Matrix (A.T) with shape (3, 2):
[[1 4]
 [2 5]
 [3 6]]

Verifying (A.T).T == A:
[[1 2 3]
 [4 5 6]]


### Matrix Multiplication (Dot Product)


To multiply two matrices, A and B, the number of columns in A must equal the number of rows in B. If A is m x n and B is n x p, the resulting matrix C will be m x p.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication using the @ operator (preferred)
C = A @ B

print(f"Matrix A:\n{A}\n")
print(f"Matrix B:\n{B}\n")
print(f"Result of A @ B:\n{C}")

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Result of A @ B:
[[19 22]
 [43 50]]


## Properties of Matrix Multiplication

## Not Commutative

Matrix multiplication is generally not commutative, meaning A @ B is not the same as B @ A.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C1 = A @ B
C2 = B @ A

print(f"A @ B:\n{C1}\n")
print(f"B @ A:\n{C2}\n")
print(f"Is A @ B == B @ A?  {np.array_equal(C1, C2)}")

A @ B:
[[19 22]
 [43 50]]

B @ A:
[[23 34]
 [31 46]]

Is A @ B == B @ A?  False


### Associative Property

Matrix multiplication is associative: (A @ B) @ C = A @ (B @ C).

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 1], [2, 3]])

result1 = (A @ B) @ C
result2 = A @ (B @ C)

print(f"(A @ B) @ C:\n{result1}\n")
print(f"A @ (B @ C):\n{result2}\n")
print(f"Are they equal? {np.array_equal(result1, result2)}")

(A @ B) @ C:
[[215  85]
 [487 193]]

A @ (B @ C):
[[215  85]
 [487 193]]

Are they equal? True


### Distributive Property

Matrix multiplication is distributive: (A + B) @ C = A @ C + B @ C.

In [ ]:
# Using the same matrices A, B, C from above

result1 = (A + B) @ C
result2 = (A @ C) + (B @ C)

print(f"(A + B) @ C:\n{result1}\n")
print(f"A @ C + B @ C:\n{result2}\n")
print(f"Are they equal? {np.array_equal(result1, result2)}")

(A + B) @ C:
[[ 70  30]
 [114  46]]

A @ C + B @ C:
[[ 70  30]
 [114  46]]

Are they equal? True


### Transpose of a Product

The transpose of a product of matrices is the product of their transposes in reverse order: (A @ B)ᵀ = Bᵀ @ Aᵀ.

In [ ]:
# Using the same matrices A, B from above

result1 = (A @ B).T
result2 = B.T @ A.T

print(f"(A @ B).T:\n{result1}\n")
print(f"B.T @ A.T:\n{result2}\n")
print(f"Are they equal? {np.array_equal(result1, result2)}")

(A @ B).T:
[[19 43]
 [22 50]]

B.T @ A.T:
[[19 43]
 [22 50]]

Are they equal? True
