## Importing libraries

In [ ]:
import numpy as np

## Create Data

In [ ]:
A = np.array([
    [5, 2],
    [2, 2]
])

print(" Original Symmetric Matrix (A) ")
print(A)

 Original Symmetric Matrix (A) 
[[5 2]
 [2 2]]


# Spectral Decomposition

## Eigen Decomposition

In [ ]:
# np.linalg.eig() finds the eigenvalues and eigenvectors
# 'eigenvalues' is a 1D array of λ values
# 'Q' is a 2D matrix where each column is an eigenvector
eigenvalues, Q = np.linalg.eig(A)

# To create the diagonal matrix Lambda, we use np.diag()
Lambda = np.diag(eigenvalues)

# Get the transpose of the eigenvector matrix
Q_transpose = Q.T

print(" Decomposition Factors ")
print(f"Eigenvectors (Q):\n{Q}\n")
print(f"Eigenvalues (Λ):\n{Lambda}\n")
print(f"Transpose of Q (Q.T):\n{Q_transpose}\n")

 Decomposition Factors 
Eigenvectors (Q):
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]

Eigenvalues (Λ):
[[6. 0.]
 [0. 1.]]

Transpose of Q (Q.T):
[[ 0.89442719  0.4472136 ]
 [-0.4472136   0.89442719]]



## Reconstruct the Original Matrix

In [ ]:
# We will multiply the factors back together.
# A = Q @ Λ @ Q.T
A_reconstructed = Q @ Lambda @ Q_transpose

print("--- Reconstruction ---")
print(f"Reconstructed Matrix (Q @ Λ @ Q.T):\n{A_reconstructed}\n")

--- Reconstruction ---
Reconstructed Matrix (Q @ Λ @ Q.T):
[[5. 2.]
 [2. 2.]]



## Verify

In [ ]:
# We check if the reconstructed matrix is "all close" to the original.
# This is necessary because of tiny floating-point math inaccuracies.
is_close = np.allclose(A, A_reconstructed)
print(is_close)

True


# Singular Value Decomposition

## Singular Value Decomposition

In [ ]:
# np.linalg.svd() finds the singular values and singular vectors
# 'U' is the left singular matrix
# 's' is a 1D array of singular values
# 'Vt' is the transpose of the right singular matrix
U, s, Vt = np.linalg.svd(A)

# To create the diagonal matrix Sigma, we use np.diag()
# Note: Sigma will have the same shape as A if A is not square
Sigma = np.diag(s)

print(" Decomposition Factors ")
print(f"Left Singular Vectors (U):\n{U}\n")
print(f"Singular Values (s):\n{s}\n")
print(f"Transpose of Right Singular Vectors (Vt):\n{Vt}\n")

 Decomposition Factors 
Left Singular Vectors (U):
[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]

Singular Values (s):
[6. 1.]

Transpose of Right Singular Vectors (Vt):
[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]



## Reconstruct the Matrix

In [ ]:
# To reconstruct the original matrix, we multiply the factors back together: A = U @ Sigma @ Vt
A_reconstructed_svd = U @ Sigma @ Vt

print(f"Reconstructed Matrix (U @ Σ @ Vt):\n{A_reconstructed_svd}\n")

Reconstructed Matrix (U @ Σ @ Vt):
[[5. 2.]
 [2. 2.]]



## Verify

In [ ]:
# Verify the reconstruction
is_close_svd = np.allclose(A, A_reconstructed_svd)
print(is_close_svd)

True
